# Change these first
owner: fluff663 # Your GitHub organization or username, where this repository lives
repo: SylviaSMPStatus # The name of this repository

sites:
  - name: Sylvia SMP
    check: "tcp-ping"
    url: mcs.sylvy.me
    port: 25565
  - name: DynMap
    url: http://dynmap.sylvy.me
  - name: Private Server
    check: "tcp-ping"
    url: $PRIVATESMPIP
    port: $PRIVATESMPPORT
  - name: Mail Server
    url: $MAILSERVERURL
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sylvy.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sylvia SMP
  introTitle: "This is the status page for the **Sylvia SMP**"
  introMessage: This page may take up to 5 minutes to update after server status changes. If something is down we are most likely already aware of and working on it please do not spam us trying to tell us.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
